export const COMPANY_ALIASES: Record<string, string> = {
  'snapchat': 'snap',
  'twitter': 'x',
  'medianet': 'media-net',
  'ola-cabs': 'ola',
  'hrt': 'hudson-river-trading',
  'bookingcom': 'booking-com',
  'wissen': 'wissen-technology',
  'citi': 'citigroup',
  'lowe': 'lowes',
  'virtu': 'virtu-financial',
  'airbus-se': 'airbus',
  'otterai': 'otter-ai',
  'ponyai': 'pony-ai',
  'apolloio': 'apollo-io',
  'larsen--toubro': 'larsen-toubro',
  'sumologic': 'sumo-logic',
  'tower-research': 'tower-research-capital',
  'cruise-automation': 'cruise',
  'national-payments-coorperation-india': 'national-payments-corporation-of-india',
  'edelweiss-group': 'edelweiss',
  'lendingkart-technologies': 'lendingkart',
  'veeva-systems': 'veeva',
};
